# Generated by Django 5.1.6 on 2025-02-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_proyect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='product',
            name='album',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
