# Generated by Django 5.1.6 on 2025-02-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_proyect', '0003_alter_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
